remote_theme: Bilal2453/cayman-docs
#theme: jekyll-theme-cayman
title: "UT NodeJS"
description: "웹 프로그래밍 응용 2023"
show_downloads: false

navigation:
  name_over_title: true
  strip_par: true
  sanitize: true
  h_min: 3
  h_max: 6

# add this plugin to gems
gems: ["jekyll-multiple-languages"]
# if you want to use pagination, you should add jekyll-paginate into gems
# and make sure it is in front of jekyll-multiple-languages
# gems:           ['jekyll-paginate', 'jekyll-multiple-languages']

# The all languages used
languages: ["en", "ko"]

# If not config, the first item of languages will be used as the default.
language_default: "en"
